<?php
return array (
  'app' => 'Admin',
  'model' => 'Setting',
  'action' => 'default',
  'data' => '',
  'type' => '0',
  'status' => '0',
  'name' => '设置',
  'icon' => 'cogs',
  'remark' => '',
  'listorder' => '7',
  'children' => 
  array (
    array (
      'app' => 'Admin',
      'model' => 'Setting',
      'action' => 'userdefault',
      'data' => '',
      'type' => '0',
      'status' => '1',
      'name' => '个人信息',
      'icon' => '',
      'remark' => '',
      'listorder' => '0',
      'children' => 
      array (
        array (
          'app' => 'Admin',
          'model' => 'User',
          'action' => 'userinfo',
          'data' => '',
          'type' => '1',
          'status' => '1',
          'name' => '修改信息',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
          'children' => 
          array (
            array (
              'app' => 'Admin',
              'model' => 'User',
              'action' => 'userinfo_post',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '修改信息提交',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
            ),
          ),
        ),
        array (
          'app' => 'Admin',
          'model' => 'Setting',
          'action' => 'password',
          'data' => '',
          'type' => '1',
          'status' => '1',
          'name' => '修改密码',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
          'children' => 
          array (
            array (
              'app' => 'Admin',
              'model' => 'Setting',
              'action' => 'password_post',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '提交修改',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
            ),
          ),
        ),
        array (
          'app' => 'Admin',
          'model' => 'Points',
          'action' => 'index',
          'data' => '',
          'type' => '1',
          'status' => '1',
          'name' => '我的积分',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
          'children' => 
          array (
            array (
              'app' => 'Admin',
              'model' => 'Points',
              'action' => 'listpoint',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '积分明细',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
            ),
          ),
        ),
        array (
          'app' => 'Admin',
          'model' => 'Points',
          'action' => 'listpoint1',
          'data' => '',
          'type' => '1',
          'status' => '0',
          'name' => '积分审核',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
          'children' => 
          array (
            array (
              'app' => 'Admin',
              'model' => 'Points',
              'action' => 'edit',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '审核',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
            ),
            array (
              'app' => 'Admin',
              'model' => 'Points',
              'action' => 'edit_post',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '提交',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
            ),
          ),
        ),
        array (
          'app' => 'Admin',
          'model' => 'Points',
          'action' => 'add',
          'data' => '',
          'type' => '1',
          'status' => '0',
          'name' => '添加积分',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
          'children' => 
          array (
            array (
              'app' => 'Admin',
              'model' => 'Points',
              'action' => 'add_post',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '提交',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
            ),
          ),
        ),
      ),
    ),
    array (
      'app' => 'Admin',
      'model' => 'Mailer',
      'action' => 'default',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'name' => '邮箱设置',
      'icon' => '',
      'remark' => '',
      'listorder' => '0',
      'children' => 
      array (
        array (
          'app' => 'Admin',
          'model' => 'Mailer',
          'action' => 'index',
          'data' => '',
          'type' => '1',
          'status' => '1',
          'name' => 'SMTP配置',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
          'children' => 
          array (
            array (
              'app' => 'Admin',
              'model' => 'Mailer',
              'action' => 'index_post',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '提交配置',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
            ),
          ),
        ),
        array (
          'app' => 'Admin',
          'model' => 'Mailer',
          'action' => 'active',
          'data' => '',
          'type' => '1',
          'status' => '0',
          'name' => '邮件模板',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
          'children' => 
          array (
            array (
              'app' => 'Admin',
              'model' => 'Mailer',
              'action' => 'active_post',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '提交模板',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
            ),
          ),
        ),
      ),
    ),
    array (
      'app' => 'Admin',
      'model' => 'Main',
      'action' => 'getVersion',
      'data' => '',
      'type' => '0',
      'status' => '0',
      'name' => '检查更新',
      'icon' => '',
      'remark' => '',
      'listorder' => '0',
    ),
    array (
      'app' => 'Admin',
      'model' => 'Setting',
      'action' => 'languages',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'name' => '多语言设置',
      'icon' => '',
      'remark' => '',
      'listorder' => '1',
    ),
    array (
      'app' => 'Content',
      'model' => 'Models',
      'action' => 'index',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'name' => '模型管理',
      'icon' => '',
      'remark' => '',
      'listorder' => '2',
    ),
    array (
      'app' => 'Admin',
      'model' => 'DemoTem',
      'action' => 'index',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'name' => '模板管理',
      'icon' => '',
      'remark' => '',
      'listorder' => '3',
    ),
    array (
      'app' => 'Socialplatform',
      'model' => 'Indexadmin',
      'action' => 'reminder',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'name' => '域名和服务器到期提醒',
      'icon' => '',
      'remark' => '',
      'listorder' => '5',
    ),
    array (
      'app' => 'Socialplatform',
      'model' => 'Indexadmin',
      'action' => 'technical',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'name' => '技术顾问',
      'icon' => 'asterisk',
      'remark' => '',
      'listorder' => '6',
    ),
    array (
      'app' => 'Admin',
      'model' => 'Setting',
      'action' => 'logo',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'name' => 'logo管理',
      'icon' => 'wheelchair',
      'remark' => '',
      'listorder' => '10',
    ),
  ),
);