<?php
return array (
  'app' => 'Statistics',
  'model' => 'Report',
  'action' => 'main',
  'data' => '',
  'type' => '0',
  'status' => '1',
  'name' => '统计分析',
  'icon' => 'line-chart',
  'remark' => '',
  'listorder' => '2',
  'children' => 
  array (
    array (
      'app' => 'Statistics',
      'model' => 'Articlestatistics',
      'action' => 'statisticsarticle',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'name' => '文章统计',
      'icon' => '',
      'remark' => '',
      'listorder' => '0',
    ),
    array (
      'app' => 'Statistics',
      'model' => 'Productsstatistics',
      'action' => 'statisticsProducts',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'name' => '产品统计',
      'icon' => '',
      'remark' => '',
      'listorder' => '1',
    ),
    array (
      'app' => 'Statistics',
      'model' => 'Foreignvis',
      'action' => 'index',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'name' => '外商浏览量统计',
      'icon' => '',
      'remark' => '',
      'listorder' => '2',
    ),
    array (
      'app' => 'Statistics',
      'model' => 'Keywordsrank',
      'action' => 'index',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'name' => '关键词排名查询',
      'icon' => '',
      'remark' => '',
      'listorder' => '3',
    ),
    array (
      'app' => 'Statistics',
      'model' => 'Links',
      'action' => 'index',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'name' => '发布链接统计',
      'icon' => '',
      'remark' => '',
      'listorder' => '4',
    ),
    array (
      'app' => 'Statistics',
      'model' => 'GoogleApi',
      'action' => 'index',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'name' => '谷歌API',
      'icon' => '',
      'remark' => '',
      'listorder' => '5',
    ),
    array (
      'app' => 'Statistics',
      'model' => 'Report',
      'action' => 'index',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'name' => '生成统计报告',
      'icon' => '',
      'remark' => '',
      'listorder' => '6',
      'children' => 
      array (
        array (
          'app' => 'Statistics',
          'model' => 'Report',
          'action' => 'creport',
          'data' => '',
          'type' => '1',
          'status' => '0',
          'name' => '生成报告预览',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
          'children' => 
          array (
            array (
              'app' => 'Statistics',
              'model' => 'Report',
              'action' => 'zcpppdf',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '生成报告',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
            ),
          ),
        ),
        array (
          'app' => 'Statistics',
          'model' => 'Report',
          'action' => 'commentlist',
          'data' => '',
          'type' => '1',
          'status' => '0',
          'name' => '报告评论列表',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
          'children' => 
          array (
            array (
              'app' => 'Statistics',
              'model' => 'Report',
              'action' => 'editcomment',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '修改评论',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
            ),
            array (
              'app' => 'Statistics',
              'model' => 'Report',
              'action' => 'edit_post',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '修改评论提交',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
            ),
            array (
              'app' => 'Statistics',
              'model' => 'Report',
              'action' => 'delete',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '删除评论',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
            ),
          ),
        ),
        array (
          'app' => 'Statistics',
          'model' => 'Report',
          'action' => 'addcomment',
          'data' => '',
          'type' => '1',
          'status' => '0',
          'name' => '新增评论',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
          'children' => 
          array (
            array (
              'app' => 'Statistics',
              'model' => 'Report',
              'action' => 'add_post',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '新增评论提交',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
            ),
          ),
        ),
      ),
    ),
    array (
      'app' => 'Statistics',
      'model' => 'inquiryStatistics',
      'action' => 'statisticsInquiry',
      'data' => '',
      'type' => '1',
      'status' => '0',
      'name' => '询盘统计',
      'icon' => '',
      'remark' => '',
      'listorder' => '11',
    ),
  ),
);