<?php
return array (
  'app' => 'Gadgets',
  'model' => 'Currency',
  'action' => 'default',
  'data' => '',
  'type' => '1',
  'status' => '1',
  'name' => '工作助手',
  'icon' => 'steam-square',
  'remark' => '',
  'listorder' => '6',
  'children' => 
  array (
    array (
      'app' => 'Gadgets',
      'model' => 'Currency',
      'action' => 'index',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'name' => '货币汇率',
      'icon' => '',
      'remark' => '',
      'listorder' => '0',
    ),
    array (
      'app' => 'Gadgets',
      'model' => 'Ip',
      'action' => 'index',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'name' => 'IP地址查询',
      'icon' => '',
      'remark' => '',
      'listorder' => '0',
    ),
    array (
      'app' => 'Gadgets',
      'model' => 'Worldtime',
      'action' => 'index',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'name' => '世界时间',
      'icon' => '',
      'remark' => '',
      'listorder' => '1',
    ),
    array (
      'app' => 'Gadgets',
      'model' => 'Customs',
      'action' => 'index',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'name' => '海关',
      'icon' => '',
      'remark' => '',
      'listorder' => '2',
    ),
    array (
      'app' => 'Gadgets',
      'model' => 'Exchagerate',
      'action' => 'index',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'name' => '汇率查询',
      'icon' => '',
      'remark' => '',
      'listorder' => '3',
    ),
    array (
      'app' => 'Gadgets',
      'model' => 'Translate',
      'action' => 'index',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'name' => '翻译',
      'icon' => '',
      'remark' => '',
      'listorder' => '4',
    ),
  ),
);